### ISSUE TITLE
Segfault in svd

### ISSUE THREAD

**Issue by syting** [JuliaLang/LinearAlgebra.jl#147]
In release-0.3 I get a segfault in openblas when running svd

```
using TestImages, ImageView    
img = testimage("cameraman")
pixels = convert(Array{Float32}, img.data)
svd(pixels)
```

yields

```
signal (11): Segmentation fault: 11
.L1_39 at /Users/syt/julia/usr/lib/libopenblas.dylib (unknown line)
signal (10): Bus error: 10
.L1_39 at /Users/syt/julia/usr/lib/libopenblas.dylib (unknown line)
signal (11): Segmentation fault: 11
.L1_39 at /Users/syt/julia/usr/lib/libopenblas.dylib (unknown line)
Bus error: 10
```

This runs fine when I exclude ImageView

**Comment by andreasnoack** [comment]
What is your `versioninfo()`?

**Comment by syting** [comment]
Julia Version 0.3.3-pre+78

Commit 75b347b\* (2014-11-19 10:23 UTC)

Platform Info:

  System: Darwin (x86_64-apple-darwin14.0.0)

  CPU: Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz

  WORD_SIZE: 64

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)

  LAPACK: libopenblas

  LIBM: libopenlibm

  LLVM: libLLVM-3.3

**Comment by andreasnoack** [comment]
I cannot reproduce this on neither Haswell nor Nehalem, but I'm trying to get access to a Sandybridge machine to see if it is specific for that architecture. If someone else with a Sandybridge machine could try to run the example, it would also be helpful.

**Comment by ViralBShah** [comment]
Cc @xianyi

**Comment by staticfloat** [comment]
I have a Haswell Mac Mini, and I can reproduce!  This is a weird one.

I've saved `pixels` as [crash.csv](https://gist.githubusercontent.com/staticfloat/c8b0663ae8537dad2236/raw/38b0cc6274549cb26c56ea26c52a52814362e8d9/crash.csv), and the following is enough to trigger the segfault:

```
z = readdlm("crash.csv")
using ImageView
svd(convert(Array{Float32},z))
```

Note that `using ImageView` is important, I don't get the segfault without it.  Here's a backtrace:

```
julia> svd(convert(Array{Float32},z))

signal (11): Segmentation fault: 11
.L1_39 at /usr/local/opt/openblas-julia/lib/libopenblas.dylib (unknown line)
Process 20329 stopped
* thread JuliaLang/julia#1: tid = 0x2587d9, 0x000000010738628e libopenblas.dylib`.L1_39 + 14, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x11a7d1000)
    frame #0: 0x000000010738628e libopenblas.dylib`.L1_39 + 14
libopenblas.dylib`.L1_39 + 14:
-> 0x10738628e:  vaddps (%r15), %xmm4, %xmm4
   0x107386293:  vaddps 0x4(%r15), %xmm5, %xmm5
   0x107386299:  vmovss %xmm4, (%r15)
   0x10738629e:  vmovss %xmm5, 0x4(%r15)
(lldb) bt
* thread JuliaLang/julia#1: tid = 0x2587d9, 0x000000010738628e libopenblas.dylib`.L1_39 + 14, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x11a7d1000)
  * frame #0: 0x000000010738628e libopenblas.dylib`.L1_39 + 14
(lldb) thread info
thread JuliaLang/julia#1: tid = 0x2587d9, 0x000000010738628e libopenblas.dylib`.L1_39 + 14, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x11a7d1000)
```

@andreasnoack if you want SSH access to this mac mini, email me your public key and I'll give you access.  Unfortunately, I can't get a backtrace in `julia-debug`, as I can't get the segfault to trigger in `julia-debug`.  _sigh._

**Comment by ViralBShah** [comment]
Hmm, doesn't crash for me, with or without `ImageView`. I didn't realize what all installing ImageView would bring along, and I am kind of surprised that it all just worked! Nice work @staticfloat.

**Comment by staticfloat** [comment]
@ViralBShah are you running a Haswell processor?

**Comment by ViralBShah** [comment]
I believe so - it is a late 2013 macbook pro. Is there a quick way to tell?

**Comment by staticfloat** [comment]
`versioninfo()` should tell you, from the OpenBLAS output.

**Comment by ViralBShah** [comment]
Ha, I now remember that. Haswell is what I have.

**Comment by xianyi** [comment]
@andreasnoack , I just create an account for you on OpenBLAS sandy bridge machine.

**Comment by andreasnoack** [comment]
@syting Did you install Julia with homebrew?

**Comment by staticfloat** [comment]
@andreasnoack I don't think this is Homebrew related.  First off, his paths don't look very Homebrew-like above.  Secondly, I can trigger the segfault in the `release-0.3` compiled-from-source version of Julia sitting in `~/src/julia-0.3`.

**Comment by andreasnoack** [comment]
Confirmed. For some reason it didn't get triggered when I pasted all four lines, but running the `svd` alone triggers it.

Now I'll `c` and `enter` a billion times one more, to get through the the non-related and caught throws from the dependency packages.

**Comment by ihnorton** [comment]
@andreasnoack see http://docs.julialang.org/en/latest/devdocs/debuggingtips/#loading-a-particular-file

**Comment by andreasnoack** [comment]
@ihnorton Thanks. I'll invest some time in improving my debugging skills to avoid the `(c+enter)*1e9` thing.

**Comment by andreasnoack** [comment]
The packages are unrelated to the problem. I can trigger it by calling `svd` enough times, e.g.

``` julia
julia> for i = 1:10; svd(float32(randn(512,512)));end
```

So far, the problem appears to be Mac specific as I haven't been able to reproduce it on a Sandybridge machine running Ubuntu.

**Comment by andreasnoack** [comment]
...and if multithreading is turned off with `blas_set_num_threads(1)` it doesn't segfault.

@xianyi It appears to be a multithreading bug in OpenBLAS caused by repeated calls to `sgesdd` only, not `d`, `c` or `z`. It also appears to be Mac specific as I cannot reproduce it on your Sandybridge machine. Do you need the exact specs of the machine that I'm able to get to segfault?

**Comment by xianyi** [comment]
@andreasnoack , yes, please give me a hit to reproduce segfault on Mac.

**Comment by syting** [comment]
@andreasnoack Seems like you've already moved past this, but I compiled from source. FWIW I saw something similar installing from homebrew and dmg.

**Comment by andreasnoack** [comment]
@xianyi It appears to be a problem for Sandybridge Macs only and related to multithreading. There also seems to be a relation to array sized of powers of two, i.e. the smallest array I can get to segfault is 256x256. All array from 257 to 511 are fine and then 512 segfaults again.

Unfortunately, I cannot get the segfault from a Fortran program, only when I call the routine from Julia, but I think our wrapper is correct because it doesn't segfault when I turn off multithreading.

**Comment by xianyi** [comment]
@andreasnoack ,  please give me the julia code. I think I can debug it on my Mac by setting TARGET=SANDYBRIDGE

**Comment by andreasnoack** [comment]
@xianyi It is simply `for i = 1:10; svd(float32(randn(512,512)));end`. Please let me know if you have any questions to the Julia source.

**Comment by xianyi** [comment]
I can reproduce on my mac. Which LAPACK function dose the `svd` call in julia?

**Comment by andreasnoack** [comment]
sgesdd

Den mandag den 1. december 2014 skrev Zhang Xianyi <notifications@github.com

**Comment by xianyi** [comment]
@andreasnoack ， how could I debug `sgemm_64_`?
After `objconv`, the gdb cannot refer `sgemm_64_` to `OpenBLAS/interface/gemm.c` C code. Instead, the gdb turns to debug `sgemm_64_` assembly codes, which is very hard to debugging.

**Comment by tkelman** [comment]
Ouch, that is unfortunate, I hadn't thought about debugging issues from the symbol rename. I wonder whether objconv can fix up the debugging info...

Does this problem happen with a Homebrew version of Julia? I believe we're not using 64 bit ints there.

**Comment by xianyi** [comment]
@tkelman , should I try Julia 0.3.3 version?

**Comment by tkelman** [comment]
@xianyi if you can reproduce the segfault there, ~~we're not renaming symbols in 0.3.3 so it's worth trying~~

edit: wait no I misremembered, I think we backported the rename before 0.3.3, but in Homebrew version of Julia it won't apply due to 32 bit integer sizes

**Comment by xianyi** [comment]
Hi all,
please try OpenBLAS develop branch. I think I already fixed this bug.

**Comment by tkelman** [comment]
Thanks for the fix @xianyi. Looks like we should bump to latest OpenBLAS version then (PR incoming). Anyone who was able to reproduce this, did it happen on 0.4-dev as well?

**Comment by andreasnoack** [comment]
I'm trying to test this right now, but I keep getting these errors when I set the OpenBLAS version to develop. Can you give me a hint here, @tkelman?

```
  "_zscal_64_", referenced from:
      _znapps_ in znapps.o
      _zneupd_ in zneupd.o
  "_ztrevc_64_", referenced from:
      _zneigh_ in zneigh.o
      _zneupd_ in zneupd.o
  "_ztrmm_64_", referenced from:
      _zneupd_ in zneupd.o
  "_ztrsen_64_", referenced from:
      _zneupd_ in zneupd.o
  "_zunm2r_64_", referenced from:
      _zneupd_ in zneupd.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[4]: *** [libarpack.la] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [arpack-ng-3.1.5/.libs/libarpack.dylib] Error 2
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
```

**Comment by andreasnoack** [comment]
Oh wait. I'll try to clean ARPACK and see what happens.

**Comment by tkelman** [comment]
That's related to JuliaLang/julia#8734. I think I should refactor that a bit, make it so you can turn off the symbol renaming in `Make.user` if you want to.

**Comment by andreasnoack** [comment]
Do you have any idea why the ARPACK build cannot find OpenBLAS?

```
checking for sgemm_ in -lblas... no
checking for sgemm_ in -lmkl... no
checking for sgemm_ in -framework vecLib... no
checking for sgemm_ in -lcxml... no
checking for sgemm_ in -ldxml... no
checking for sgemm_ in -lscs... no
checking for sgemm_ in -lcomplib.sgimath... no
checking for sgemm_ in -lblas... (cached) no
checking for sgemm_ in -lblas... (cached) no
configure: error: Cannot find BLAS libraries
```

The dylib is there and I can find the symbol in it.

**Comment by tkelman** [comment]
Can you gist `deps/arpack-ng-3.1.5/config.log` ?

**Comment by tkelman** [comment]
You may also need to `make -C deps distclean-arpack` instead of just `clean-arpack` to get configure to re-run

**Comment by andreasnoack** [comment]
I managed to build with 0.2.13 and I can confirm that the bug is fixed so when the OpenBLAS version change is merged we can close this issue. Thanks @xianyi.
